### ISSUE TITLE
Can't use solvent masks in linux

### ISSUE THREAD

**Issue by MilitaoLucas** [pcxod/olex2#5]
When using shelxl for refinement, I can't apply a mask in olex2. I get the error:
CANNOT OPEN FILE file.fab  
file.fab has the same name as my ins file. I am using the normal version of olex2 that I downloaded from the website.

**Comment by Luke2Sky** [comment]
Just tried in the newer alpha release. Same problem.

**Comment by Luke2Sky** [comment]
I now tried running the exact same experiment in windows 10 and it worked fine.

**Comment by Luke2Sky** [comment]
I am stupid.

**Comment by Luke2Sky** [comment]
I am very confused. I thoutght it had stop working because I forgot to specify the solvent, but it is very weird how I keep getting the same error even though I did it now. In Windows it is working much better.

**Comment by FlorianKleemiss** [comment]
is there any error messages before shelx complains about the missing .fab file? Does the file exist? is there output in the Olex2 windows about the mask being created? You can type "log" and get the complete log file of your current session to see more details before shelx is called.

**Comment by FlorianKleemiss** [comment]
Does the mask work with normal olex2.refine?

**Comment by pcxod** [comment]
It should work in the same way. But for FAB file - the mask needs to be computed. There could be a problem with file name letter cases though.

**Comment by Luke2Sky** [comment]
My bad, I should've tried it before creating this issue. I am kind of new at using olex2. It works fine using olex2.ref. Now I don't know if the problem is with the ShelXL linux binaries or with olex2 itself.

**Comment by Luke2Sky** [comment]
> is there any error messages before shelx complains about the missing .fab file? Does the file exist? is there output in the Olex2 windows about the mask being created? You can type "log" and get the complete log file of your current session to see more details before shelx is called.

**Comment by Luke2Sky** [comment]
The file name is 05_23_myname.fab and it is not empty. When running in windows, using shelxl it worked perfectly. But it is possible that this is a problem with shelxl itself or with some missing olex2 dependence.

**Comment by FlorianKleemiss** [comment]
is there any capital letters different? What @pcxod was saying is that on windows file names are not case sensitive, but on linux they are, hence this would be a hint to investigate

**Comment by Luke2Sky** [comment]
Every letter in the name of the file is uncapitalized. I don't know if this is related, but $PYTHONHOME points to olex2 directory, but the sh script python3 is empty.

**Comment by Luke2Sky** [comment]
Something I shold've already mentioned is that I am using Fedora 40 in both computers I tried.

**Comment by FlorianKleemiss** [comment]
An Error with python would have shown much earlier.
So if the file with the correct name exists and is filled with information it should be something about how the filename is forwarded to SHELXL. Is is in a folder with some kind of special characters along the path?

**Comment by Luke2Sky** [comment]
> An Error with python would have shown much earlier. So if the file with the correct name exists and is filled with information it should be something about how the filename is forwarded to SHELXL. Is is in a folder with some kind of special characters along the path?

I thought that might be the problem, so before opening this issue, I transfered everything from my winetricks directory (I did some reprocessing in CrysalisPro) to my Linux directory. About Python errors, I always get stuff like this:
```
Unresolved reference: py.GetParam(snum.grow.short)
Unresolved reference: py.GetParam(snum.grow.selection)
Unresolved reference: py.GetParam(snum.grow.vdw)
Included file does not exist: '/home/myname/.olex2/data/745d26b59d0d20ddea5b298af6168afa/custom.xld'
Unresolved reference: py.GetParam(snum.grow.short)
UNRESOLVED: 'py.GetParam(snum.grow.short)'
Unresolved reference: py.GetParam(snum.grow.selection)
UNRESOLVED: 'py.GetParam(snum.grow.selection)'
Unresolved reference: py.GetParam(snum.grow.vdw)
UNRESOLVED: 'py.GetParam(snum.grow.vdw)'
reload help
```
And this:
```
Traceback (most recent call last):
  File "/home/myname/olex2/util/pyUtil/olexFunctions.py", line 692, in func
    retVal = f(*args, **kwds)
  File "/home/myname/olex2/util/pyUtil/PyToolLib/htmlTools.py", line 1199, in MakeHoverButton
    TI.produce_buttons(button_names=[name], btn_type="_%s" %btn_type)
  File "/home/myname/olex2/util/pyUtil/PyToolLib/PilTools.py", line 1382, in produce_buttons
    self.make_images_from_fb_png()
  File "/home/myname/olex2/util/pyUtil/PyToolLib/PilTools.py", line 1012, in make_images_from_fb_png
    self.make_buttons()
  File "/home/myname/olex2/util/pyUtil/PyToolLib/PilTools.py", line 1271, in make_buttons
    self.produce_buttons(button_names, "", self.sf, width=width)
  File "/home/myname/olex2/util/pyUtil/PyToolLib/PilTools.py", line 1430, in produce_buttons
    self.save_with_checking_for_needed()
  File "/home/myname/olex2/util/pyUtil/PyToolLib/PilTools.py", line 1917, in save_with_checking_for_needed
    OlexVFS.save_image_to_olex(image, name, 2)
  File "/home/myname/olex2/util/pyUtil/PyToolLib/OlexVFS.py", line 36, in save_image_to_olex
    image.save(ImageToOlexWriter, "PNG")
AttributeError: 'NoneType' object has no attribute 'save'
```
